// test/run-tests.js — v2.10 harness verification.
//
// Boots the REAL server (staged with exactly the Docker COPY file set, so a
// pass here also proves Issue #1's fix ships every module the server needs)
// against two mock Moonraker printers — one U1-profile, one generic/Sovol
// profile — and drives the 2.9 feature set over plain HTTP:
//
//   A: 2.8.1→2.9 migration, type CRUD + reuse-lock rules, per-type directory
//      split, upload/print routing, queue tagging, capability detection,
//      cross-class block, send-time class guard, missing-folder boot warning
//   B: server boots + serves from the Docker file set (no full checkout)
//   C: spool_id engine — snapshot search, bind (swatch / manual+local), tag
//      resolve round-trip, persistence across restart, forget
//   C loadout: load-to-printer mapping (assign/move/replace/clear, caps range
//      check, restart persistence, forget auto-unload)
//   Beta/diag: beta flag on non-builtin types; /api/diagnostics bundle shape,
//      ring buffer, IPv4/token sanitization, tolerant printer-log tails
//   V: version consistency across server.js / index.html / package.json
//
// Run: npm test   (needs `npm install` first for express)
//
// NOTE (Rule #1): passing this harness makes a workstream "built", not
// "shippable". The live gates remain: A → real SV06 Plus ACE, B → Docker on
// Pi/NAS, C → Web NFC tag scan on Android over HTTPS.

"use strict";

const { spawn } = require("child_process");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { createMock } = require("./mock-moonraker.js");

const REPO = path.join(__dirname, "..");
const HUB_PORT = 45990;
const HUB = "http://127.0.0.1:" + HUB_PORT;

let PASS = 0, FAIL = 0;
function ok(cond, name, detail) {
  if (cond) { PASS++; console.log("  ✓ " + name); }
  else { FAIL++; console.log("  ✗ " + name + (detail !== undefined ? "  → " + JSON.stringify(detail).slice(0, 300) : "")); }
}
const jget = async (p) => { const r = await fetch(HUB + p); return { status: r.status, body: await r.json().catch(() => null) }; };
const jpost = async (p, b) => {
  const r = await fetch(HUB + p, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(b || {}) });
  return { status: r.status, body: await r.json().catch(() => null) };
};
const sleep = ms => new Promise(r => setTimeout(r, ms));

// Minimal multi- and single-color gcode fixtures (Orca-style config tail).
const GCODE_MULTI = [
  "; generated by OrcaSlicer",
  "G28", "T0", "G1 X1", "T1", "G1 X2", "T2", "G1 X3",
  "; filament_colour = #FF0000;#00FF00;#0000FF;#FFFFFF",
  "; filament_type = PLA;PLA;PLA;PLA",
  "; filament used [g] = 10.0;12.5;3.2;0",
  "; estimated printing time (normal mode) = 1h 2m"
].join("\n");
const GCODE_SINGLE = [
  "; generated by OrcaSlicer",
  "G28", "G1 X1",
  "; filament_colour = #FF0000",
  "; filament_type = PLA",
  "; filament used [g] = 8.8",
  "; estimated printing time (normal mode) = 22m"
].join("\n");

// Minimal STORED-method zip builder — enough to fabricate a 3MF fixture for
// the analyze endpoint (a 3MF is just a zip with config members).
function crc32(buf) {
  let t = crc32.T;
  if (!t) {
    t = crc32.T = new Int32Array(256);
    for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1; t[n] = c; }
  }
  let c = ~0;
  for (let i = 0; i < buf.length; i++) c = t[(c ^ buf[i]) & 0xFF] ^ (c >>> 8);
  return ~c >>> 0;
}
function buildZip(files) { // [{name, data:Buffer}]
  const locals = [], centrals = [];
  let off = 0;
  for (const f of files) {
    const name = Buffer.from(f.name), data = f.data, crc = crc32(data);
    const lh = Buffer.alloc(30);
    lh.writeUInt32LE(0x04034b50, 0); lh.writeUInt16LE(20, 4); lh.writeUInt16LE(0, 6); lh.writeUInt16LE(0, 8);
    lh.writeUInt32LE(0, 10); lh.writeUInt32LE(crc, 14); lh.writeUInt32LE(data.length, 18); lh.writeUInt32LE(data.length, 22);
    lh.writeUInt16LE(name.length, 26); lh.writeUInt16LE(0, 28);
    const ch = Buffer.alloc(46);
    ch.writeUInt32LE(0x02014b50, 0); ch.writeUInt16LE(20, 4); ch.writeUInt16LE(20, 6); ch.writeUInt16LE(0, 8); ch.writeUInt16LE(0, 10);
    ch.writeUInt32LE(0, 12); ch.writeUInt32LE(crc, 16); ch.writeUInt32LE(data.length, 20); ch.writeUInt32LE(data.length, 24);
    ch.writeUInt16LE(name.length, 28); ch.writeUInt32LE(off, 42);
    locals.push(lh, name, data);
    centrals.push(Buffer.concat([ch, name]));
    off += 30 + name.length + data.length;
  }
  const cd = Buffer.concat(centrals);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0); eocd.writeUInt16LE(files.length, 8); eocd.writeUInt16LE(files.length, 10);
  eocd.writeUInt32LE(cd.length, 12); eocd.writeUInt32LE(off, 16);
  return Buffer.concat([...locals, cd, eocd]);
}

// Stage the hub with EXACTLY the Dockerfile's COPY set (Workstream B check).
const DOCKER_SET = ["server.js", "parser.js", "auth.js", "fs-colors.js", "tunnel.js", "rfid.js", "filament-swatches.json", "package.json"];
function stageHub(dir) {
  fs.mkdirSync(dir, { recursive: true });
  for (const f of DOCKER_SET) fs.copyFileSync(path.join(REPO, f), path.join(dir, f));
  fs.cpSync(path.join(REPO, "scripts"), path.join(dir, "scripts"), { recursive: true });
  fs.cpSync(path.join(REPO, "public"), path.join(dir, "public"), { recursive: true });
  // Dependencies are copied INTO the staged dir rather than reached via
  // NODE_PATH — module resolution across a network-mapped repo drive (SMB)
  // hangs in spawned children on Windows (hardware-verified 2026-08-16:
  // require("express") over \\server\share freezes indefinitely in a child
  // process while working fine interactively). The Docker image gets
  // node_modules from `npm install` anyway, so the Issue #1
  // app-file-completeness check is unchanged: the DOCKER_SET list above is
  // still the thing under test.
  fs.cpSync(path.join(REPO, "node_modules"), path.join(dir, "node_modules"), { recursive: true });
}

let CHILD = null;
async function startHub(dir) {
  CHILD = spawn(process.execPath, ["server.js"], {
    cwd: dir, stdio: ["ignore", "pipe", "pipe"],
    env: { ...process.env }
  });
  let log = "";
  CHILD.stdout.on("data", d => log += d);
  CHILD.stderr.on("data", d => log += d);
  for (let i = 0; i < 60; i++) {
    await sleep(250);
    try { const r = await fetch(HUB + "/api/version"); if (r.ok) return log; } catch {}
    if (CHILD.exitCode !== null) throw new Error("hub exited early:\n" + log);
  }
  throw new Error("hub never came up:\n" + log);
}
async function stopHub() {
  if (!CHILD) return;
  CHILD.kill("SIGTERM");
  await new Promise(r => { CHILD.on("exit", r); setTimeout(r, 2000); });
  CHILD = null;
}

(async () => {
  // v2.10: run the print-start/complete watcher at 400 ms so the filament-
  // memory section can drive a full lifecycle in seconds (production: 15 s).
  process.env.U1HUB_POLL_MS = "400";
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "u1hub-test-"));
  const hubDir = path.join(tmp, "app");
  stageHub(hubDir);

  // Mock printers: one of each class.
  const mockU1 = createMock("u1");
  const mockSv = createMock("generic");
  const portU1 = await mockU1.listen(0);
  const portSv = await mockSv.listen(0);

  // ---- 2.8.1-style state on disk (pre-migration) ---------------------------
  const gcodeDir = path.join(hubDir, "gcode");
  fs.mkdirSync(gcodeDir, { recursive: true });
  fs.writeFileSync(path.join(gcodeDir, "multi.gcode"), GCODE_MULTI);
  fs.writeFileSync(path.join(gcodeDir, "single.gcode"), GCODE_SINGLE);
  fs.writeFileSync(path.join(hubDir, "config.json"), JSON.stringify({
    gcodeFolder: "./gcode", port: HUB_PORT,
    printers: [
      { name: "U1-mock", url: "http://127.0.0.1:" + portU1 },
      { name: "SV-mock", url: "http://127.0.0.1:" + portSv }
    ]
  }, null, 2));
  fs.writeFileSync(path.join(hubDir, "queue.json"), JSON.stringify([{ id: "q1", file: "multi.gcode", added: 1 }]));
  fs.writeFileSync(path.join(hubDir, "printlog.json"), JSON.stringify({ "multi.gcode": 1700000000000 }));

  console.log("\n== B: boot from the Docker COPY file set ==");
  await startHub(hubDir);
  let r = await jget("/api/version");
  ok(r.body && r.body.version === "2.10.0", "server boots from Docker file set, reports 2.10.0", r.body);
  r = await fetch(HUB + "/"); ok(r.ok, "serves index.html");
  r = await fetch(HUB + "/fs-colors.html"); ok(r.ok, "serves fs-colors.html (fs-colors.js present)");
  r = await jget("/api/auth/status"); ok(r.status === 200, "auth.js mounted", r.status);
  r = await jget("/api/tunnel/status"); ok(r.status === 200, "tunnel.js mounted", r.status);

  console.log("\n== A: 2.8.1 → 2.9 migration ==");
  r = await jget("/api/types");
  ok(r.body && r.body.types.length === 1 && r.body.types[0].slug === "u1" && r.body.types[0].builtin, "built-in U1 type registered", r.body);
  ok(r.body.types[0].accent === "#FFB200", "U1 keeps today's exact accent", r.body.types[0].accent);
  r = await jget("/api/config");
  ok(r.body.printers.every(p => p.type === "u1"), "existing printers tagged as U1 instances", r.body.printers);
  r = await jget("/api/queue");
  ok(r.body.queue.length === 1 && r.body.queue[0].type === "u1", "pre-2.9 queue entries tagged u1", r.body.queue);
  r = await jget("/api/files?type=u1");
  ok(r.body.files.some(f => f.name === "multi.gcode" && f.lastPrinted === 1700000000000), "flat printlog migrated under u1 (lastPrinted intact)", r.body.files);
  ok(fs.existsSync(path.join(gcodeDir, "multi.gcode")), "no files moved on migration");

  console.log("\n== A: type CRUD + reuse-lock rules ==");
  r = await jpost("/api/types", { label: "SV06 Plus ACE" });
  ok(r.status === 200 && r.body.type.slug === "sv06-plus-ace", "add type generates slug + folder", r.body);
  ok(fs.existsSync(path.join(gcodeDir, "sv06-plus-ace")), "auto-created <base>/<slug>/ subfolder");
  ok(r.body.type.accent && r.body.type.accent !== "#FFB200", "new type auto-assigned a distinct accent", r.body.type.accent);
  r = await jpost("/api/types", { label: "SV06 Plus ACE" });
  ok(r.status === 409, "slug/folder collision rejected with clear message", r.body);
  r = await jpost("/api/types/update", { slug: "sv06-plus-ace", label: "Sovol SV06 Plus ACE" });
  ok(r.status === 200, "display label rename ok");
  r = await jget("/api/files?type=sv06-plus-ace");
  ok(r.status === 200 && r.body.files.length === 0, "rename did NOT move the folder (slug immutable)", r.body);
  r = await jpost("/api/types/delete", { slug: "u1" });
  ok(r.status === 400, "built-in U1 type cannot be deleted", r.body);

  console.log("\n== A: per-type directory split ==");
  fs.writeFileSync(path.join(gcodeDir, "sv06-plus-ace", "sv-single.gcode"), GCODE_SINGLE);
  fs.writeFileSync(path.join(gcodeDir, "sv06-plus-ace", "sv-multi.gcode"), GCODE_MULTI);
  r = await jget("/api/files?type=u1");
  ok(!r.body.files.some(f => /^sv-/.test(f.name)), "U1 view does not see the other type's files", r.body.files.map(f => f.name));
  r = await jget("/api/files?type=sv06-plus-ace");
  ok(r.body.files.length === 2 && r.body.files.every(f => /^sv-/.test(f.name)), "new type sees only its own subfolder", r.body.files.map(f => f.name));
  r = await jget("/api/map?file=sv-multi.gcode&type=sv06-plus-ace");
  ok(r.body && r.body.usedIdx && r.body.usedIdx.length === 3, "/api/map reads from the type's folder", r.body && r.body.usedIdx);

  console.log("\n== A: instances into types + capability detection ==");
  let cfg = (await jget("/api/config")).body;
  cfg.printers[1].type = "sv06-plus-ace";
  r = await jpost("/api/config", { gcodeFolder: cfg.gcodeFolder, printers: cfg.printers });
  ok(r.status === 200 && r.body.printers[1].type === "sv06-plus-ace", "printer reassigned to new type", r.body.printers);
  r = await jget("/api/fleet");
  const fU1 = r.body.find(p => p.id === 0), fSv = r.body.find(p => p.id === 1);
  ok(fU1 && fU1.ptype === "u1" && fSv && fSv.ptype === "sv06-plus-ace", "fleet records carry type", r.body.map(p => p.ptype));
  ok(fU1.caps && fU1.caps.multiColor === true && fU1.caps.heads === 4, "U1-class caps detected from print_task_config", fU1.caps);
  ok(fSv.caps && fSv.caps.multiColor === false && fSv.caps.heads === 1, "generic Klipper caps detected (single extruder, no color API)", fSv.caps);
  ok(Array.isArray(fSv.heads) && fSv.heads.length === 0, "no fabricated U1 heads on a generic printer", fSv.heads);
  ok(fU1.heads.length === 4 && fU1.heads[1].vendor === "Snapmaker", "U1 heads decode intact (official spool identity)", fU1.heads[1]);

  console.log("\n== A: upload/print routing + queue tagging ==");
  r = await jpost("/api/queue", { file: "sv-single.gcode", type: "sv06-plus-ace" });
  ok(r.status === 200 && r.body.queue.some(e => e.file === "sv-single.gcode" && e.type === "sv06-plus-ace"), "queue add carries type", r.body.queue);
  r = await jget("/api/queue?type=u1");
  ok(!r.body.queue.some(e => e.file === "sv-single.gcode"), "queue filters by type", r.body.queue);
  r = await jpost("/api/print", { file: "sv-single.gcode", printer: 1, start: true, type: "sv06-plus-ace" });
  ok(r.status === 200 && r.body.jobId, "single-color job to single-extruder: no class objection", r.body);
  await sleep(600);
  ok(mockSv.state.uploads.some(u => u.filename === "sv-single.gcode"), "file uploaded to the RIGHT mock printer", mockSv.state.uploads);
  ok(mockU1.state.uploads.length === 0, "nothing leaked to the other class's printer");
  ok(mockSv.state.gcodeScripts.some(s => /^SDCARD_PRINT_FILE/.test(s)), "print started via SDCARD_PRINT_FILE", mockSv.state.gcodeScripts);
  ok(!mockSv.state.gcodeScripts.some(s => /SET_PRINT_EXTRUDER_MAP/.test(s)), "no U1 mapping macros sent to a generic printer");
  r = await jget("/api/queue?type=sv06-plus-ace");
  ok(!r.body.queue.some(e => e.file === "sv-single.gcode"), "queue entry auto-removed on start", r.body.queue);

  console.log("\n== A: cross-class block + send-time class guard ==");
  r = await jpost("/api/print", { file: "multi.gcode", printer: 1, type: "u1" });
  ok(r.status === 400 && /different printer type/.test(r.body.error || ""), "structural cross-class block (U1 file → Sovol)", r.body);
  mockSv.state.printState = "standby";
  r = await jpost("/api/print", { file: "sv-multi.gcode", printer: 1, type: "sv06-plus-ace" });
  ok(r.status === 409 && r.body.classWarning, "multi-color job to single-extruder → warn (guard catches wrong-folder drops)", r.body);
  r = await jpost("/api/print", { file: "sv-multi.gcode", printer: 1, type: "sv06-plus-ace", force: true });
  ok(r.status === 200 && r.body.jobId, "explicit force overrides the warning", r.body);
  r = await jpost("/api/print", { file: "single.gcode", printer: 0, type: "u1" });
  ok(r.status === 200 && r.body.note && /Single-color/.test(r.body.note), "single-color to U1 → soft note only", r.body);

  console.log("\n== C: spool_id engine (snapshot, bind, resolve) ==");
  r = await jget("/api/filaments/meta");
  ok(r.body && r.body.count > 2000, "bundled snapshot loaded (" + (r.body && r.body.count) + " swatches)", r.body);
  r = await jget("/api/filaments/search?q=blizzard+white&page_size=5");
  ok(r.body.results.length >= 1 && r.body.results[0].color_source === "measured", "snapshot search finds swatches (measured)", r.body.results[0]);
  ok(/FilamentColors/.test(r.body.attribution || ""), "attribution present in search responses");
  const swatch = r.body.results.find(s => s.id === 4835) || r.body.results[0];
  ok(Array.isArray(swatch.lab) && typeof swatch.lab[0] === "number", "trimmed record carries measured LAB", swatch.lab);
  ok(swatch.material_variant, "material_variant present (display label)", swatch);

  const UID = "04:A3:1C:9F:22:80:00";
  r = await jpost("/api/spools/resolve", { uid: UID });
  ok(r.body.unknown === true, "unknown tag → association prompt path", r.body);
  r = await jpost("/api/spools/bind", { uid: UID, swatch_id: swatch.id });
  ok(r.status === 200 && r.body.spool_id && r.body.spool.hex === swatch.hex, "one snapshot pick binds brand+material+hex+LAB+temps", r.body);
  const SPID = r.body.spool_id;
  r = await jpost("/api/spools/resolve", { uid: "04a31c9f228000" });   // same tag, bare-hex form (USB-reader style)
  ok(r.body.known && r.body.spool_id === SPID, "UID normalization: colon-hex and bare-hex resolve to the same spool", r.body);
  r = await jpost("/api/spools/resolve", { spool_id: SPID });
  ok(r.body.known === true, "QR path: spool_id resolves directly (no UID involved)", r.body);
  r = await jpost("/api/spools/bind", { uid: "AA:BB:CC:DD", identity: { hex: "#123ABC", color_name: "Shop Teal" }, saveLocal: true });
  ok(r.status === 200 && r.body.spool.color_source === "user", "manual-entry fallback binds with color_source:user", r.body);
  r = await jget("/api/filaments/search?q=shop+teal");
  ok(r.body.results.some(s => s.color_name === "Shop Teal"), "manual entry saved into local color library (searchable)", r.body.results);
  // ATTACH mode: a second physical tag (vendor's built-in RFID + a Hub NTAG
  // sticker, or a serial that reads differently on another adapter) points at
  // the SAME spool instead of spawning a duplicate identity.
  r = await jpost("/api/spools/bind", { uid: "04:57:91:35:d1:2a:81", spool_id: SPID });
  ok(r.status === 200 && r.body.attached === true && r.body.spool_id === SPID, "attach: new tag joins an existing spool, identity untouched", r.body);
  r = await jpost("/api/spools/resolve", { uid: "04579135D12A81" });
  ok(r.body.known && r.body.spool_id === SPID, "attached tag resolves to the same spool", r.body);
  r = await jget("/api/spools");
  ok(r.body.spools.find(s => s.spool_id === SPID).uids.length === 2, "spool now lists both tag UIDs", r.body.spools.find(s => s.spool_id === SPID));
  r = await jpost("/api/spools/bind", { uid: "01020304", spool_id: "sp_ghost" });
  ok(r.status === 400, "attach to a nonexistent spool rejected", r.body);
  // Multi-color identities: silk duals/tris and gradients carry hexes[2–3] +
  // color_style; primary hex stays authoritative so every hex consumer works.
  r = await jpost("/api/spools/bind", { uid: "0102030405ab", identity: { hex: "#AA00AA", hexes: ["#AA00AA", "#00AAAA", "#AAAA00"], color_style: "gradient", color_name: "Rainbow Silk", brand: "Overture", material: "PLA", material_variant: "PLA Silk", hot_end_temp: 210, bed_temp: 60 } });
  ok(r.status === 200 && r.body.spool.hexes.length === 3 && r.body.spool.color_style === "gradient" && r.body.spool.hex === "AA00AA" && r.body.spool.brand === "Overture" && r.body.spool.hot_end_temp === 210,
    "multi-color bind: hexes+style+brand+material+temps all stored, primary hex = first color", r.body.spool);
  const SPMC = r.body.spool_id;
  r = await jpost("/api/spools/resolve", { uid: "0102030405AB" });
  ok(r.body.known && r.body.spool.hexes.join(",") === "AA00AA,00AAAA,AAAA00", "multi-color identity survives the resolve round-trip", r.body.spool);
  r = await jpost("/api/spools/bind", { identity: { hex: "#112233", hexes: ["#112233", "nope"], color_style: "multi", color_name: "Junk Hexes" } });
  ok(r.status === 200 && r.body.spool.hexes === null && r.body.spool.color_style === null,
    "invalid extra colors collapse to a solid (never a half-broken multi)", r.body.spool);
  await jpost("/api/spools/forget", { spool_id: r.body.spool_id });
  await jpost("/api/spools/forget", { spool_id: SPMC });

  console.log("\n== C: QR adapter (labels + spool_id resolve, no UID involved) ==");
  r = await fetch(HUB + "/labels.html"); ok(r.ok, "label sheet page served");
  r = await fetch(HUB + "/vendor/qrcode-generator.js"); ok(r.ok, "vendored QR encoder served (MIT)");
  r = await fetch(HUB + "/vendor/jsQR.js"); ok(r.ok, "vendored QR decoder served (Apache-2.0) — the iOS path");
  {
    // Full physical round trip in software: encode the label exactly as
    // labels.html does, rasterize, decode exactly as the scanner fallback
    // does, resolve the decoded payload against the running hub.
    const enc = require(path.join(REPO, "public", "vendor", "qrcode-generator.js"));
    const jsQRm = require(path.join(REPO, "public", "vendor", "jsQR.js"));
    const jsQR = jsQRm.default || jsQRm;
    const qr = (enc.qrcode || enc)(0, "M"); qr.addData("u1spool:" + SPID); qr.make();
    const n = qr.getModuleCount(), scale = 8, quiet = 4, size = (n + quiet * 2) * scale;
    const px = new Uint8ClampedArray(size * size * 4);
    for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) {
      const mx = Math.floor(x / scale) - quiet, my = Math.floor(y / scale) - quiet;
      const v = (mx >= 0 && my >= 0 && mx < n && my < n && qr.isDark(my, mx)) ? 0 : 255;
      const i = (y * size + x) * 4; px[i] = px[i + 1] = px[i + 2] = v; px[i + 3] = 255;
    }
    const dec = jsQR(px, size, size);
    ok(dec && dec.data === "u1spool:" + SPID, "QR encode → rasterize → decode round trip", dec && dec.data);
    const payload = /^u1spool:(\S+)$/.exec(dec.data);
    r = await jpost("/api/spools/resolve", { spool_id: payload[1] });
    ok(r.body.known && r.body.spool.hex === swatch.hex, "decoded label resolves to the same filament identity as the NFC tag", r.body);
  }

  console.log("\n== C: loadout (load-to-printer mapping) ==");
  // Closes the scan→bind loop: a bound spool is recorded into a physical
  // printer slot (Hub-side slots.json). One spool = one location; occupied
  // slots are replaced; range-checks ride DETECTED capabilities.
  r = await jpost("/api/slots/assign", { printer: 0, slot: 1, spool_id: SPID });
  ok(r.status === 200 && r.body.spool.hex === swatch.hex, "bound spool loads into U1 T2", r.body);
  r = await jget("/api/slots");
  let pv = r.body.printers.find(x => x.printer === 0);
  ok(pv && pv.slots["1"] && pv.slots["1"].spool_id === SPID && pv.slots["1"].spool.hex === swatch.hex,
    "slot map resolves the loaded spool's full identity", pv && pv.slots);
  r = await jpost("/api/slots/assign", { printer: 1, slot: 0, spool_id: SPID });
  ok(r.status === 200, "same spool re-loads onto the generic printer");
  r = await jget("/api/slots");
  pv = r.body.printers.find(x => x.printer === 0);
  const pv1 = r.body.printers.find(x => x.printer === 1);
  ok(!(pv.slots || {})["1"] && pv1.slots["0"] && pv1.slots["0"].spool_id === SPID,
    "physical invariant: assigning MOVED the spool (one location only)", { u1: pv.slots, sv: pv1.slots });
  r = await jpost("/api/slots/assign", { printer: 1, slot: 2, spool_id: SPID });
  ok(r.status === 400 && /1 slot/.test(r.body.error || ""), "slot beyond DETECTED head count rejected (generic = 1 extruder)", r.body);
  r = await jpost("/api/slots/assign", { printer: 0, slot: 0, spool_id: "sp_nope" });
  ok(r.status === 404, "unknown spool_id rejected", r.body);
  // Replace: bind a second spool and load it over the first one's slot.
  r = await jpost("/api/spools/bind", { identity: { hex: "#445566", color_name: "Replace Me Gray" } });
  const SPID2 = r.body.spool_id;
  r = await jpost("/api/slots/assign", { printer: 1, slot: 0, spool_id: SPID2 });
  ok(r.status === 200 && r.body.replaced && r.body.replaced.spool_id === SPID,
    "loading into an occupied slot replaces (and reports) the occupant", r.body.replaced);
  r = await jpost("/api/slots/clear", { printer: 1, slot: 0 });
  ok(r.status === 200, "slot clear");
  await jpost("/api/spools/forget", { spool_id: SPID2 });
  // Park SPID in U1 T3 — the restart section asserts this survives.
  await jpost("/api/slots/assign", { printer: 0, slot: 2, spool_id: SPID });

  console.log("\n== FS: Orca alignment (byte-exact serialization round trip) ==");
  {
    const { defString } = require(path.join(REPO, "fs-colors.js"));
    const { decodeMixedDefEntry, parseGcodeMap } = require(path.join(REPO, "parser.js"));
    // Byte-exact emit against the hardware-verified fork shapes.
    ok(defString([{ slot: 2, pct: 60 }, { slot: 4, pct: 40 }], 7) === "2,4,1,1,40,0,g,w,m2,z0,xa0,xb0,d0,o0,u7,cm0",
      "pair emits verified m2 shape, P on the SECOND filament");
    ok(defString([{ slot: 3, pct: 50 }, { slot: 1, pct: 20 }, { slot: 2, pct: 30 }], 3) === "1,2,1,1,50,0,g123,w20/30/50,m0,z0,xa0,xb0,d0,o0,u3,cm0",
      "triple emits verified m0 shape with ASCENDING g indices");
    // Decode of the exact strings that were hand-verified on the fork.
    let d = decodeMixedDefEntry("2,4,1,1,40,0,g,w,m2,z0,xa0,xb0,d0,o0,u7,cm0");
    ok(d && d.filaments.join(",") === "2,4" && d.weights.join(",") === "60,40",
      "m2 pair decodes as F2 60% + F4 40% (the previously-DROPPED format)", d);
    d = decodeMixedDefEntry("1,2,1,1,50,0,g123,w20/30/50,m0,z0,xa0,xb0,d0,o0,u3,cm0");
    ok(d && d.filaments.join(",") === "1,2,3" && d.weights.join(",") === "20,30,50", "m0 list decodes 20/30/50", d);
    // Round trip: everything we emit parses back to the identical recipe.
    const cases = [
      [{ slot: 1, pct: 55 }, { slot: 3, pct: 45 }],
      [{ slot: 2, pct: 5 }, { slot: 3, pct: 90 }, { slot: 4, pct: 5 }],
      [{ slot: 1, pct: 33 }, { slot: 2, pct: 33 }, { slot: 4, pct: 34 }]
    ];
    ok(cases.every(c => {
      const dd = decodeMixedDefEntry(defString(c, 9));
      const sorted = [...c].sort((a, b) => a.slot - b.slot);
      return dd && dd.filaments.join() === sorted.map(x => x.slot).join() && dd.weights.join() === sorted.map(x => x.pct).join();
    }), "emit → decode round trip is exact for pairs and triples");
    let threw = false;
    try { defString([{ slot: 1, pct: 60 }, { slot: 2, pct: 50 }], 1); } catch { threw = true; }
    ok(threw, "emit refuses weights that don't sum to 100 (robustness guard)");
    // Gcode-level regression: a file whose definitions hold a pair AND a triple
    // — the pair used to vanish from the Hub's FS preview.
    const g = parseGcodeMap([
      "; filament_colour = #FF0000;#00FF00;#0000FF;#FFFFFF",
      "; filament_type = PLA;PLA;PLA;PLA",
      "; filament used [g] = 5;5;5;5",
      "; mixed_filament_definitions = 2,4,1,1,40,0,g,w,m2,z0,xa0,xb0,d0,o0,u1,cm0;1,2,1,1,50,0,g123,w20/30/50,m0,z0,xa0,xb0,d0,o0,u2,cm0"
    ].join("\n"), { scanBody: false });
    ok(g.mixed.length === 2 && g.mixed[0].filaments.join() === "2,4" && g.mixed[1].filaments.join() === "1,2,3",
      "sliced-gcode FS preview now shows pair mixes too (regression fixed)", g.mixed);
  }
  // HTTP: solve returns the paste-once definitions string and honors uidStart.
  r = await jpost("/api/fs-colors/solve", { spools: ["#FF0000", "#00FF00", "#0000FF", "#FFFFFF"], targets: ["#808000", "#800080"], uidStart: 5 });
  ok(r.status === 200 && typeof r.body.definitions === "string" && r.body.definitions.includes(";"),
    "solve returns combined mixed_filament_definitions value", r.body.definitions);
  ok(/u6,cm0/.test(r.body.definitions) && !/u1,cm0/.test(r.body.definitions),
    "uid numbering continues after the project's existing definitions (uidStart)", r.body.definitions);
  // 3MF with existing fork definitions → decoded reconciliation view + maxUid.
  {
    const ps = JSON.stringify({
      filament_colour: ["#FF0000", "#00FF00", "#0000FF", "#FFFFFF"],
      mixed_filament_definitions: "2,4,1,1,40,0,g,w,m2,z0,xa0,xb0,d0,o0,u4,cm0;1,2,1,1,50,0,g123,w20/30/50,m0,z0,xa0,xb0,d0,o0,u9,cm0"
    });
    const zip = buildZip([{ name: "Metadata/project_settings.config", data: Buffer.from(ps) }]);
    const rr = await fetch(HUB + "/api/fs-colors/analyze", { method: "POST", body: zip });
    const jb = await rr.json();
    ok(rr.ok && jb.existingMixes && jb.existingMixes.length === 2 && jb.existingMixes[0].label === "F2 60% + F4 40%",
      "3MF analyze decodes the project's existing mixes (incl. pair)", jb.existingMixes);
    ok(jb.maxUid === 9, "maxUid reported for collision-free uid continuation", jb.maxUid);
    // analyze-parts: the browser-extraction path (v2.9) — same configs as
    // text, byte-identical analysis. This is what keeps huge FS projects from
    // uploading whole over the tunnel (Cloudflare caps bodies ~100 MB).
    const rp = await jpost("/api/fs-colors/analyze-parts", { projectSettings: ps, modelSettings: '<object key="extruder" value="1"/><part key="extruder" value="1"/><part key="extruder" value="2"/>' });
    ok(rp.status === 200 && JSON.stringify(rp.body.existingMixes) === JSON.stringify(jb.existingMixes) && rp.body.maxUid === 9,
      "analyze-parts (client-extracted configs) matches the whole-file path", rp.body.existingMixes);
    ok(rp.body.hasUsage === true && rp.body.colors[0].hex === "#FF0000" && rp.body.colors[0].parts === 2,
      "analyze-parts ranks usage from model_settings text", rp.body.colors);
  }

  console.log("\n== FS: base-set recommender (which spools to load) ==");
  {
    // Targets olive (#808000 = R+G) and purple (#800080 = R+B): any winning set
    // MUST contain red, green and blue. Greys are decoys that cover nothing.
    const candidates = [
      { label: "Shop Red", hex: "#FF0000", spool_id: "sp_r" },
      { label: "Gray 1", hex: "#777777" }, { label: "Gray 2", hex: "#7A7A7A" },  // near-dupe pair → dedupe
      { label: "Shop Green", hex: "#00FF00", spool_id: "sp_g" },
      { label: "Beige", hex: "#D8C8A8" },
      { label: "Shop Blue", hex: "#0000FF", spool_id: "sp_b" },
      { label: "White", hex: "#FFFFFF" }
    ];
    r = await jpost("/api/fs-colors/recommend", { targets: ["#808000", "#800080"], candidates });
    ok(r.status === 200 && r.body.sets && r.body.sets.length >= 1, "recommender returns ranked sets", r.body);
    const best = r.body.sets[0];
    const hexes = best.spools.map(s => s.hex);
    ok(["#FF0000", "#00FF00", "#0000FF"].every(h => hexes.includes(h)),
      "best load-out contains the three colors the targets actually need", hexes);
    ok(best.worst <= 2, "winning set covers the WORST target within exact range (dE " + best.worst + ")", best);
    ok(best.spools.find(s => s.hex === "#FF0000").spool_id === "sp_r",
      "recommendation names the physical roll (spool_id rides through)", best.spools);
    ok(r.body.candidateCount === 6, "near-duplicate candidates deduped (7 in → 6 considered)", r.body.candidateCount);
    ok(r.body.benchmark && r.body.benchmark.benchmark === true && r.body.benchmark.spools.length === 4,
      "ideal-CMYW benchmark row present and flagged as reference", r.body.benchmark && r.body.benchmark.spools);
    r = await jpost("/api/fs-colors/recommend", { targets: ["#808000"], candidates: candidates.slice(0, 3) });
    ok(r.status === 422, "fewer than 4 distinct candidates → clear 422", r.body);
  }

  console.log("\n== M: print-file filament memory (v2.10, content-hashed) ==");
  {
    // Earlier routing checks may have left the mock mid-"print"; settle it to
    // standby and let a poll observe that, so the next start is a genuine
    // standby→printing transition.
    mockU1.state.printState = "standby"; mockU1.state.filename = "";
    await sleep(1000);
    // Own spool + loadout so the snapshot has something to remember. SPID is
    // parked in T3 for the restart section — T1 is free.
    r = await jpost("/api/spools/bind", { identity: { hex: "#C0FFEE", color_name: "Memory Mint", brand: "TestCo" } });
    const FMID = r.body.spool_id;
    await jpost("/api/slots/assign", { printer: 0, slot: 0, spool_id: FMID });
    // A file with unique bytes — the memory key is CONTENT, not the name.
    const FMBODY = GCODE_SINGLE + "\n; fmem fixture " + Date.now();
    fs.writeFileSync(path.join(gcodeDir, "fmemtest.gcode"), FMBODY);
    r = await jget("/api/filament-memory?file=fmemtest.gcode&type=u1");
    ok(r.status === 200 && r.body.known === false && r.body.hash, "never-printed file → known:false (with its content hash)", r.body);
    // Start → the watcher snapshots {hash, loadout}; complete → it records.
    r = await jpost("/api/print", { file: "fmemtest.gcode", printer: 0, start: true, type: "u1" });
    ok(r.status === 200 && r.body.jobId, "print kicked off for the fixture", r.body);
    await sleep(1200);
    ok(mockU1.state.printState === "printing", "mock is printing the fixture", mockU1.state.printState);
    mockU1.state.printState = "complete";
    await sleep(1200);
    r = await jget("/api/filament-memory?file=fmemtest.gcode&type=u1");
    ok(r.body.known === true && r.body.spools.length === 2,
      "completed print recorded the full loadout (T1 fixture spool + parked T3)", r.body.spools);
    const remT1 = (r.body.spools || []).find(s => s.slot === 0);
    ok(remT1 && remT1.spool_id === FMID && remT1.hex === "C0FFEE" && remT1.missing === false,
      "remembered slot names the physical roll with live identity", remT1);
    // Rename-proof: same bytes under a new name still recall the same record.
    await jpost("/api/files/rename", { name: "fmemtest.gcode", newName: "totally-different-name.gcode", type: "u1" });
    r = await jget("/api/filament-memory?file=totally-different-name.gcode&type=u1");
    ok(r.body.known === true, "rename-proof: memory keys on content, not filename", r.body);
    // Forgotten spool degrades gracefully: returned from the snapshot, flagged.
    await jpost("/api/spools/forget", { spool_id: FMID });
    r = await jget("/api/filament-memory?file=totally-different-name.gcode&type=u1");
    ok(r.body.known === true && r.body.spools.find(s => s.slot === 0).missing === true,
      "spool forgotten since → still shown, flagged missing", r.body.spools);
    // Re-slice reset: different bytes = different job = clean history.
    fs.writeFileSync(path.join(gcodeDir, "totally-different-name.gcode"), FMBODY + "\nG1 X99 ; re-sliced");
    r = await jget("/api/filament-memory?file=totally-different-name.gcode&type=u1");
    ok(r.body.known === false, "re-sliced file (new bytes) correctly starts with no history", r.body);
    // The record itself lives in printlog.json (never-commit list) on disk.
    const plraw = JSON.parse(fs.readFileSync(path.join(hubDir, "printlog.json"), "utf8"));
    ok(plraw.__filaments && Object.keys(plraw.__filaments).length >= 1,
      "memory persisted under printlog.json's reserved __filaments key", Object.keys(plraw.__filaments || {}));
    ok(plraw.u1 && plraw.u1["fmemtest.gcode"] === undefined && typeof plraw.u1["totally-different-name.gcode"] === "number",
      "last-printed stamp migrated with the rename, untouched by fmem sharing the file", Object.keys(plraw.u1 || {}));
    r = await jget("/api/diagnostics?logs=0");
    ok(r.body.counts && r.body.counts.filamentMemories >= 1, "diagnostics bundle counts filament memories", r.body.counts);
    // Tidy: settle the mock and drop the fixture so later sections see the
    // same world they always did.
    mockU1.state.printState = "standby"; mockU1.state.filename = "";
    await sleep(1000);
    await jpost("/api/files/delete", { name: "totally-different-name.gcode", type: "u1" });
  }

  console.log("\n== M: Phomemo M110 label layers (v2.10, hardware-verified 2026-08-25) ==");
  {
    r = await fetch(HUB + "/labels.html"); const lbl = await r.text();
    ok(r.ok && /M110 40×30/.test(lbl), "labels page carries the M110 40×30 mm format toggle");
    ok(/@page m110page\{ size:40mm 30mm/.test(lbl), "M110 format sizes each label as its own 40×30 mm page");
    ok(/"bluetooth" in navigator/.test(lbl) && /data-bt=/.test(lbl),
      "Web Bluetooth layer feature-detected with per-label print buttons");
    // The double-verified protocol, byte for byte (USB RAW print on the real
    // M110S + byte-identical to the field-tested phomymo reference):
    ok(/0x1b, 0x4e, 0x0d/.test(lbl) && /0x1b, 0x4e, 0x04/.test(lbl) && /0x1f, 0x11, 0x0a/.test(lbl)
      && /0x1d, 0x76, 0x30, 0x00/.test(lbl) && /0x1f, 0xf0, 0x05, 0x00/.test(lbl) && !/0x1b, 0x40/.test(lbl),
      "verified protocol bytes: speed/density/gap-media header, GS v 0 raster, 1F F0 footer, NO ESC @");
    ok(/new Uint8Array\(bytes\)\.buffer/.test(lbl),
      "regression guard: BLE writes copy into a fresh buffer (the subarray-view bug that ate the first print)");
    ok(/PAD_LEFT: 8/.test(lbl), "M110S right-aligned paper path: rows pad 8 zero bytes left");
    ok(/navigator\.share/.test(lbl) && /toBlob/.test(lbl) && /image\/png/.test(lbl),
      "\ud83d\udce4 share-to-app layer present (iOS path): pre-thresholded PNG into the OS share sheet");
    ok(!/api\/label/.test(lbl) && !/labelPrinter/.test(lbl),
      "bridge fully dropped: no server print endpoint or queue config referenced anywhere");
  }

  console.log("\n== M2: duplicate-color tool mapping (v2.10) ==");
  {
    // A 4-tool file where two tools carry the SAME palette hex (Orca can't
    // merge extruders; the user recolored T1 and T3 both to white).
    fs.writeFileSync(path.join(gcodeDir, "dup4.gcode"), [
      "; generated by OrcaSlicer",
      "G28", "T0", "G1 X1", "T1", "G1 X2", "T2", "G1 X3", "T3", "G1 X4",
      "; filament_colour = #FF0000;#FFFFFF;#0000FF;#FFFFFF",
      "; filament_type = PLA;PLA;PLA;PLA",
      "; filament used [g] = 10.0;2.0;3.2;2.0",
      "; estimated printing time (normal mode) = 1h"
    ].join("\n"));
    // DIFFERENT colors on one head must still refuse — and the message must
    // name the exact per-index hexes, which is also the hexByIdx alignment
    // proof (misaligned indices would surface the wrong colors here).
    r = await jpost("/api/print", { file: "dup4.gcode", printer: 0, type: "u1", map: { 0: 0, 1: 2, 2: 2, 3: 3 } });
    ok(r.status === 400 && /#FFFFFF/.test(r.body.error) && /#0000FF/.test(r.body.error) && /T3/.test(r.body.error),
      "different colors sharing a head → refused, naming T3 and both exact hexes (hexByIdx aligned)", r.body);
    // A hex the file can't prove → refuse (never assume safety).
    fs.writeFileSync(path.join(gcodeDir, "dup3.gcode"), [
      "; generated by OrcaSlicer",
      "G28", "T0", "G1 X1", "T1", "G1 X2", "T2", "G1 X3", "T3", "G1 X4",
      "; filament_colour = #FF0000;#00FF00;#0000FF",
      "; filament_type = PLA;PLA;PLA",
      "; filament used [g] = 1;1;1",
      "; estimated printing time (normal mode) = 1h"
    ].join("\n"));
    r = await jpost("/api/print", { file: "dup3.gcode", printer: 0, type: "u1", map: { 2: 1, 3: 1 } });
    ok(r.status === 400 && /couldn't be read/.test(r.body.error),
      "unreadable palette hex on a shared head → refused (can't prove it's safe)", r.body);
    // IDENTICAL colors sharing a head → allowed, and the printer must be told
    // about the physical head ONCE. Assert on what the mock actually received.
    mockU1.state.gcodeScripts.length = 0;
    r = await jpost("/api/print", { file: "dup4.gcode", printer: 0, type: "u1", map: { 0: 0, 1: 3, 2: 2, 3: 3 } });
    ok(r.status === 200 && r.body.jobId, "identical colors sharing a head → accepted", r.body);
    let job = null;
    for (let i = 0; i < 40 && !(job && job.done); i++) { await sleep(250); job = (await jget("/api/print-status?job=" + r.body.jobId)).body; }
    ok(job && job.done && !job.error && job.result && job.result.mapped === 4,
      "mapping job completed, all 4 tools mapped", job);
    const mapScript = mockU1.state.gcodeScripts.find(s => /SET_PRINT_USED_EXTRUDERS/.test(s)) || "";
    const used = (/SET_PRINT_USED_EXTRUDERS EXTRUDERS=([\d,]+)/.exec(mapScript) || [])[1];
    ok(used === "0,3,2", "USED_EXTRUDERS deduped as received by the printer (0,3,2 — not 0,3,2,3)", used);
    ok(/SET_PRINT_EXTRUDER_MAP CONFIG_EXTRUDER=1 MAP_EXTRUDER=3/.test(mapScript)
      && /SET_PRINT_EXTRUDER_MAP CONFIG_EXTRUDER=3 MAP_EXTRUDER=3/.test(mapScript),
      "both white tools mapped to the same physical head in the macros", mapScript.split("\n"));
    await jpost("/api/files/delete", { name: "dup4.gcode", type: "u1" });
    await jpost("/api/files/delete", { name: "dup3.gcode", type: "u1" });
  }

  console.log("\n== R: loadout replay, server half — setcolor honesty (v2.10) ==");
  {
    // The spool-first replay UI lives client-side; its hardware gate (cross-
    // slot replay on a real printer) stays live per Rule #1. What the harness
    // CAN prove is the server half every replay Apply rides on: presence
    // checks, the official-spool lock, and — the 2.10 point — that success is
    // only ever claimed off the printer's own read-back.
    r = await jpost("/api/setcolor", { printer: 0, slot: 0, hex: "#123ABC" });
    ok(r.status === 200 && r.body.ok === true && mockU1.state.ptc.filament_color_rgba[0] === "123ABCFF",
      "writable tray: color written AND the printer itself reports it", r.body);
    r = await jpost("/api/setcolor", { printer: 0, slot: 2, hex: "#123ABC" });
    ok(r.status === 409 && /No filament loaded in slot T3/.test(r.body.error),
      "empty tray → refused before any write (replay's honest-apply precondition)", r.body);
    r = await jpost("/api/setcolor", { printer: 0, slot: 1, hex: "#123ABC" });
    ok(r.status === 409 && /official/.test(r.body.error),
      "official RFID spool → friendly color-locked refusal", r.body);
    // Firmware silently refuses → the Hub must surface it, never claim success.
    mockU1.state.dropColorWrites = true;
    r = await jpost("/api/setcolor", { printer: 0, slot: 0, hex: "#654321" });
    ok(r.status === 502 && /not confirmed/.test(r.body.error) && mockU1.state.ptc.filament_color_rgba[0] === "123ABCFF",
      "silently-dropped write → 502 'not confirmed' off the read-back — no false ✓", r.body);
    mockU1.state.dropColorWrites = false;
    // Mid-print, colors are untouchable — replay must refuse, not queue.
    mockU1.state.printState = "printing";
    r = await jpost("/api/setcolor", { printer: 0, slot: 0, hex: "#0F0F0F" });
    ok(r.status === 409 && /printing/.test(r.body.error), "printing → refused (replay can't fire mid-print)", r.body);
    mockU1.state.printState = "standby"; mockU1.state.filename = "";
    await sleep(600);
  }

  console.log("\n== A+C: persistence across restart ==");
  // Also plant a missing-folder scenario for the boot warning check.
  await jpost("/api/types", { label: "Ghost Type" });
  await stopHub();
  fs.rmSync(path.join(gcodeDir, "ghost-type"), { recursive: true, force: true });
  await startHub(hubDir);
  r = await jget("/api/types");
  const ghost = r.body.types.find(t => t.slug === "ghost-type");
  ok(ghost && /missing/i.test(ghost.warning || ""), "missing folder at boot → per-type warning, no crash, no silent recreate", ghost);
  ok(!fs.existsSync(path.join(gcodeDir, "ghost-type")), "hub did not silently recreate the missing folder");
  ok(r.body.types.find(t => t.slug === "sv06-plus-ace"), "type bindings survive restart");
  r = await jpost("/api/spools/resolve", { uid: UID });
  ok(r.body.known && r.body.spool.hex === swatch.hex, "UID → filament identity survives restart (spools.json)", r.body);
  r = await jget("/api/slots");
  ok((r.body.printers.find(x => x.printer === 0).slots || {})["2"]?.spool_id === SPID,
    "loadout survives restart (slots.json)", r.body.printers[0]);
  r = await jget("/api/files?type=sv06-plus-ace");
  ok(r.body.files.length >= 2, "type folder binding still locked after restart", r.body.files.length);

  console.log("\n== A: delete/unbind preserves files ==");
  r = await jpost("/api/types/delete", { slug: "sv06-plus-ace" });
  ok(r.status === 409, "delete refused while printers still belong to the type", r.body);
  cfg = (await jget("/api/config")).body;
  cfg.printers[1].type = "u1";
  await jpost("/api/config", { gcodeFolder: cfg.gcodeFolder, printers: cfg.printers });
  r = await jpost("/api/types/delete", { slug: "sv06-plus-ace" });
  ok(r.status === 200, "delete succeeds once instances are reassigned", r.body);
  ok(fs.existsSync(path.join(gcodeDir, "sv06-plus-ace", "sv-single.gcode")), "gcode files PRESERVED on disk after type delete");
  r = await jpost("/api/spools/forget", { spool_id: SPID });
  ok(r.status === 200, "spool forget");
  r = await jpost("/api/spools/resolve", { uid: UID });
  ok(r.body.unknown === true, "forgotten spool's tag resolves as unknown again", r.body);
  r = await jget("/api/slots");
  ok(r.body.printers.every(p => !Object.values(p.slots || {}).some(v => v.spool_id === SPID)),
    "forgetting a spool also unloads it from every slot", r.body.printers.map(p => p.slots));

  console.log("\n== Beta flag + diagnostics bundle ==");
  await jpost("/api/types", { label: "Beta Probe" });
  r = await jget("/api/types");
  ok(r.body.types.find(t => t.slug === "u1").beta === false && r.body.types.find(t => t.slug === "beta-probe").beta === true,
    "non-builtin types flagged beta:true, U1 is not", r.body.types.map(t => [t.slug, t.beta]));
  await jpost("/api/types/delete", { slug: "beta-probe" });
  // Ring buffer is IN-MEMORY by design (the Hub never writes a log file), so
  // the restart above legitimately emptied it. Generate fresh events in THIS
  // process lifetime: a loadout assign (also re-proves slots endpoints on the
  // restarted hub) — caps detection already re-fired serving /api/slots.
  r = await jpost("/api/spools/bind", { identity: { hex: "#0A0B0C", color_name: "Diag Probe" } });
  const SPID3 = r.body.spool_id;
  await jpost("/api/slots/assign", { printer: 0, slot: 0, spool_id: SPID3 });
  // The bundle: correct shape, ring buffer populated by real events, and the
  // sanitizer proven — the mocks live on 127.0.0.1 and NO raw IPv4 may ship.
  r = await fetch(HUB + "/api/diagnostics");
  const diagRaw = await r.text();
  const diag = JSON.parse(diagRaw);
  ok(r.ok && diag.hub && diag.hub.version === "2.10.0", "diagnostics bundle reports hub version", diag.hub);
  ok(Array.isArray(diag.log) && diag.log.some(l => /caps\[/.test(l.msg)),
    "ring buffer captured capability-detection events", (diag.log || []).slice(-3));
  ok(diag.log.some(l => /loadout:/.test(l.msg)), "ring buffer captured loadout events", (diag.log || []).slice(-3));
  ok(diag.counts && diag.counts.slotsAssigned >= 1, "bundle counts the loadout state", diag.counts);
  await jpost("/api/spools/forget", { spool_id: SPID3 });
  ok(diag.printers.length === 2 && diag.printers[0].alias === "printer-1" && diag.printers[0].caps,
    "printers listed by alias with detected caps", diag.printers);
  ok(!/\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/.test(diagRaw) && !diagRaw.includes("127.0.0.1"),
    "sanitizer scrubbed every IPv4 from the serialized bundle");
  ok(diag.klipperLogs["printer-1"] && diag.klipperLogs["printer-1"].klippy.ok === false && diag.klipperLogs["printer-1"].klippy.note,
    "missing printer log → tolerant note, export still succeeds (Rule #1: fork path unverified)", diag.klipperLogs["printer-1"]);
  ok(/slots\.json/.test(fs.readFileSync(path.join(REPO, ".gitignore"), "utf8")), "slots.json on the never-commit list");

  console.log("\n== V: version discipline ==");
  const vSrv = /const VERSION = "([^"]+)"/.exec(fs.readFileSync(path.join(REPO, "server.js"), "utf8"))[1];
  const vUi = /const VERSION = "([^"]+)"/.exec(fs.readFileSync(path.join(REPO, "public", "index.html"), "utf8"))[1];
  const vPkg = JSON.parse(fs.readFileSync(path.join(REPO, "package.json"), "utf8")).version;
  ok(vSrv === vUi && vUi === vPkg, "server.js / index.html / package.json versions match (" + [vSrv, vUi, vPkg].join(" / ") + ")");
  ok(vSrv === "2.10.0", "version is 2.10.0");
  const all = ["server.js", "public/index.html", "package.json", "Dockerfile", "docker-compose.yml", "rfid.js"].map(f => fs.readFileSync(path.join(REPO, f), "utf8")).join("");
  ok(!/2\.8\.2/.test(all), "no dead 2.8.2 version string anywhere");

  await stopHub();
  await mockU1.close(); await mockSv.close();
  fs.rmSync(tmp, { recursive: true, force: true });

  console.log("\n" + PASS + " passed, " + FAIL + " failed\n");
  process.exit(FAIL ? 1 : 0);
})().catch(async e => { console.error("\nHARNESS ERROR:", e); await stopHub().catch(() => {}); process.exit(1); });
